---
# handlers file for roles/backend
- name: Copy index file
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ backend_root_path }}index.html"
    owner: root
    group: root
    mode: '0664'
